version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFlowRenderingProject
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: newOnPrem1
  version: 10.15.0.0.674
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: testServiceAndTxRenderingOnprem
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: DesignerStepsInCloudEditorPackage
  gitServerName: test
  gitUrl: https://github.com/santhu736852
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: DesignerStepsInCloudEditorTxPipelinePackage
  gitServerName: test
  gitUrl: https://github.com/santhu736852
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testflowrendering.integrations:parentFlow
  packages:
  - name: TestFlowRenderingProject
    version: "1.0"
  - name: newOnPrem1
    version: 10.15.0.0.674
- serviceName: new_folder:new_flowservice
  packages:
  - name: newOnPrem1
    version: 10.15.0.0.674
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
